# Generated by Django 4.2.1 on 2023-05-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0002_alter_assignment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
